# Generated by Django 3.2.9 on 2021-12-31 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthUsuario',
        ),
        migrations.DeleteModel(
            name='TipoUsuario',
        ),
    ]
