# Generated by Django 3.2.9 on 2021-12-18 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alongamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(upload_to='imagem/alongamento')),
            ],
        ),
        migrations.CreateModel(
            name='Cosmetico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('C', 'Cabeça'), ('R', 'Rosto'), ('P', 'Pescoço')], max_length=2)),
                ('imagem', models.ImageField(upload_to='imagem/cosmetico')),
            ],
        ),
        migrations.CreateModel(
            name='Pomodoro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('S', 'Pausado'), ('P', 'Em Progresso'), ('I', 'Inativo'), ('C', 'Concluido'), ('E', 'Encerrado')], default='I', max_length=1)),
                ('duracao', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='UID',
            new_name='uid',
        ),
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido', models.CharField(max_length=255)),
                ('cor_olhos', models.CharField(max_length=7)),
                ('cor_pele', models.CharField(max_length=7)),
                ('usuario_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
    ]
