# Generated by Django 3.2.9 on 2022-01-14 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historico',
            name='usuario_uid',
        ),
        migrations.AddField(
            model_name='historico',
            name='usuario',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
            preserve_default=False,
        ),
    ]
