# Generated by Django 3.2.9 on 2021-12-21 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211217_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='cosmeticos',
            field=models.ManyToManyField(to='core.Cosmetico'),
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('data', models.DateTimeField()),
                ('usuario_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.personagem')),
            ],
        ),
    ]
